#!/bin/sh
# Automatically added by dh_pysupport
if which update-python-modules >/dev/null 2>&1; then
	update-python-modules  American-miner.public
fi
# End automatically added section
# Automatically added by dh_installinit
if [ -x "/etc/init.d/American-miner" ]; then
	update-rc.d American-miner defaults >/dev/null
	if [ -x "`which invoke-rc.d 2>/dev/null`" ]; then
		invoke-rc.d American-miner start || exit $?
	else
		/etc/init.d/American-miner start || exit $?
	fi
fi
# End automatically added section
© 2022 GitHub, Inc.
