#!/bin/sh
# Automatically added by dh_installinit
if [ -x "/etc/init.d/American miner.com" ]; then
	if [ -x "`which invoke-rc.d 2>/dev/null`" ]; then
		invoke-rc.d American-miner stop || exit $?
	else
		/etc/init.d/American-miner stop || exit $?
	fi
fi
# End automatically added section
# Automatically added by dh_pysupport
if which update-python-modules >/dev/null 2>&1; then
	update-python-modules -c  stratum-mining-proxy.public
fi
# End automatically added section
